### ISSUE TITLE
rebecca@psilaos.org on build #10: selecting any of these 4 options should trigger Prompt 1…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/SurveillanceLaosApp#15]
Feedback from rebecca@psilaos.org : selecting any of these 4 options should trigger Prompt 1 "please refer patient for testing" screen before review/submit. right now it goes directly to review/submit.

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/5774c82ced561801003de3c2/57bc349ec88f110100b8a3fe/5b65516e-c49a-4d69-99a6-3117e7e7119d.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Tue Aug 30 2016 01:32:58 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>10</td></tr><tr><td>Device type</td><td>SCH-I545</td></tr><tr><td>Screen size</td><td>1080</td></tr><tr><td>Screen size</td><td>1080px by 1920px</td></tr><tr><td>Battery</td><td>64% Unplugged</td></tr><tr><td>Memory free</td><td>463 MB / 1807 MB</td></tr></table>

 [Link to buddybuild feedback from build 10](https://dashboard.buddybuild.com/apps/5774c82ced561801003de3c2/feedback?fid=57c4e24aa8ae9c0100fedf63&bnum=10)

**Comment by ifoche** [comment]
Sorry but, looking at the [workflow](https://drive.google.com/file/d/0BzWNKmbLqoIRU0pLMk5fOWdNQm8/view) I cannot see that behaviour. Is this a new requirement or am I missing some other document?

**Comment by rbeccapotter** [comment]
In the workflow, it would have been "Submit v.2" because the text for provider is different and we did not realize the review/submit was a popup.  I understand this needs to be built like a new question (but I don't think it changes the logic; Prompt 1a will always follow Q2). 

The artwork is here, Page 3_Prompt 1a (.ai files with and without text): https://drive.google.com/open?id=0BzWNKmbLqoIRRXg1SEE5ZGY3dlU

The correct translation is here (see Prompt 1a): https://drive.google.com/open?id=0BzWNKmbLqoIRTVdWdlpvRGtzZ1U
