### ISSUE TITLE
Export file contains no translation 

### ISSUE THREAD

**Issue by Vbouasone** [EyeSeeTea/SurveillanceLaosApp#53]
In event capture in DHIS2 the titles show in Lao, Once I downloaded or exported into CSV file those titles are strange. 
![issue_8](https://user-images.githubusercontent.com/29400470/28262844-cc6c602c-6b0e-11e7-99b7-4a390d2a1f7e.JPG)

**Comment by ifoche** [comment]
@Vbouasone that's not an Android bug, right? You're downloading that from the server and it's not related to the data, but to the metadata if I'm not bad

**Comment by Vbouasone** [comment]
You are right that is about download data from server.

**Comment by rbeccapotter** [comment]
@Vbouasone I don't think it's the metadata, I think it's relating to fonts you have access to on your computer or in Excel (maybe). For example, when I download as csv from the Event Capture app it seems to be pulling the form name (that should be Lao) not the DE name, and so I am seeing only these strange characters:
![gibberish.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57c39ad5fc48880e00600632/125516c66e82c728ace21e0d46ef9d98218791a09ce1fd0fe64de29b234324676b5ee17e27d2b72be91622500d0a47fd155a5a44fda88022a2bf6e62964e49bc8f3900299f7744eeaa880dbc00b0218e4f84b3b98f44c4ef3a23e399c2.png)

For what it's worth, when you download an Excel file from event Reports the Excel is showing everything in English as expected.
![event report english.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57c39ad5fc48880e00600632/125516c66e82c728ace21e0d46ed829f2d96c3bb8af9b051b01df59a2e4a2e602146ef696097ec22ba416f43554d4bab465c0c42f8f08879f3bf6d2488590bec80645670cf6f03b0aac04ee155e57dd205d0f4ae805ec2ee3724e28b8e4a3b1b0d1b8af75f3db2d4.png)

So anyways, we can mark this as "done" since it requires no action.

**Comment by Vbouasone** [comment]
@rbeccapotter, You are right when we download from Even report into Excel
it seem every thing is showing in English but only the *"Organisation unit
name"* does not show in Lao, even I tried with all Lao fonts that available
in Excel still they are showing in Thai without translation. can you please
check point?

[image: Inline image 1]

**Comment by rbeccapotter** [comment]
@Vbouasone since this is not an Android issue, I'm closing the issue here and switching the conversation to e-mail.
