### ISSUE TITLE
Event date vs Time Capture

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/SurveillanceLaosApp#54]
Events with Time Capture = 2017-08-01T00:29:41.179+0100 render as event dates = 2017/07/31. Any reason why that is? I guess that is the date EST but would NOT be the correct date of local Laos time. Maybe this would be problematic for data quality checking. I'm looking at org unit

**Comment by ifoche** [comment]
@rbeccapotter could you provide a concrete example? To be more specific, what I want to see is where are you looking for the event date, to tell you exactly how and when that date is being written.

**Comment by rbeccapotter** [comment]
I'm looking at Events from Event Capture view in https://staging.psi-mis.org for the org unit 'PH Manixok (404_17)'. Time capture/time sent DE's don't render in event reports; but I can confirm that the event dates are displaying the same in ER: https://staging.psi-mis.org/dhis-web-event-reports/index.html?id=nF1HFm2blWi

Attached is a download of the Events from Event Capture view

[eventList.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57c39ad5fc48880e00600632/125516c66e82c728ace21e0d46ed829f2d96afa09cfdfd0fe64de29b234324676b5ee17e27d2b72be91622500d0a47fd155a5a44fda88022a2bf6e62964e49bc8f3900299f7744eeaa880dbc00b0218e4f87b6b4824ac9ec3a20e399c2.xlsx)

**Comment by ifoche** [comment]
Sorry @rbeccapotter but I don't have any user with access to that OU in staging nor permission to create one. Else, our development server has not enough memory and is presenting problems when trying to change anything for the users or OUs, and the only useful dev server that I have access to with the Laos program is clone server, which restarts daily. So I will try to replicate it in clone server and let you know asap

**Comment by ifoche** [comment]
@rbeccapotter we've checked it and currently the times are set as follows:
Event Date = Time when the survey was created (when the user clicks the + button)
Time Capture = Time when the survey was completed (when the user finished the survey)

Maybe you want us to change both to the time when the survey was completed? (that way they would match)

**Comment by rbeccapotter** [comment]
Confirming event date makes sense as time when survey created
Yes, would make more sense that Time capture = when survey was created [and therefore always be the same as Event Date] ]

But I'm not 100% sure that that's the problem. I'm quite certain it did not take me 30 minutes between starting the survey and completing the survey/sending to server at 00:30. This might be a strange/isolated incident because I happened to be doing my testing just after midnight, in timezone +0100 UTC...I'll see if I can replicate it. Attached the ADB in case that helps.
[compressedData (1).zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57c39ad5fc48880e00600632/125516c66e82c728ace21e0d46eb9b97339086ba9cecbb67a549f1d461176e316546b3397f8fe62bab0021435a5849a8125e5b4dfdabdc22f7e23e758a5d5ae4d8695626d42103eee9dc4be05ce36ade0d97bcae894dcae93825e58a874a381f0d1a81ff4f78.zip)

**Comment by ifoche** [comment]
Thank you for your answer @rbeccapotter. So we will wait to see if you can replicate the problem. In terms of code changes:
1) Do you want us to change Time Capture to be when the user click on + button?
2) Do you want us to change Event Date to be the time when the survey was completed?
3) Do you want us to leave it as-is?

I guess that depending on the result of your tests and the answer to the questions above we would publish to Google Play after doing changes to the code, or after analyzing & fixing the bug if you can replicate it, or immediately if you don't want us to do any other change to the code.

**Comment by rbeccapotter** [comment]
@ifoche  Ideally, yes it should be: Event date = Time capture = time when user clicks on the +   

But I don't think that's the problem. I was able to replicate the issue in my own local Laos UTC+0700 time zone. See the highlighted events attached where capture & time sent do not match the Event Date. I tested carefully and I pushed + on the survey within one minute of completing ("Time capture") --> so I don't think the mismatch is due to a delay between clicking + and completing.  

Also, event date does not match what is seen on the Android screen (screenshot attached).

I think it might be something about how the "Event date" is being calculated to account for time zone. This is happening when the day changes in the user's timezone (e.g. Laos), but hasn't yet changed on Eastern Standard Time (UTC-0400).

![Screenshot_2017-08-09-21-00-05.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57c39ad5fc48880e00600632/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1c364167f3e795dee7921c8b378f2122e43434d0eee1e020a17b8eb8339a3b13b74d95a0fe4d03f0a7d976913a9b8834eb608be29d95d99a4fedb1294b7607caddecd5d340c011d80fe5734a59949ca50fe4fe24556a61b242e.png)

[eventList (6).xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57c39ad5fc48880e00600632/125516c66e82c728ace21e0d46ed829f2d96afa09cfdff0bf214b2d86b56357c2301a03f32dfa17de8152f02595b47ad130d5615a8fb8c2ba7e735798e5559ffcd7f1d2598694ef1e1c84afd13b0328a4a84b2b4804dc5e83f27ef838a4a3b1807119bb2.xlsx)

**Comment by ifoche** [comment]
@rbeccapotter just to confirm that we've been able to replicate the problem, related as you properly pointed to the timezone (which made us not to see it). We think it may have to do with how the server accept the string format for the event date. I'll come back to you with more info as soon as we solve it. Thanks for detecting it!

**Comment by ifoche** [comment]
@rbeccapotter we've already implemented a solution to the problem and probably tomorrow we will be in the position to generate a new release with that problem solved. Just to keep you posted

**Comment by ifoche** [comment]
Hi again @rbeccapotter. After analyzing a little bit more the problem, we've realized that in fact it was working already good. There was no mismatch in the date, but simply a problem of interpretation. If you see again your xls file, you will realize that those dates that seemed not to match in fact are the same date, but in different timezone.

The point is that the event date, creation date and those other, are server dates, and server time is in UTC. So when you ask for it it is providing you the date in UTC. While the dates DE like Time Capture is not in UTC, but it's providing you the timezone.

For example:
You had the event pj6ZytKaUvH
Event date: 7/31/2017
Time capture: 2017-08-01T00:34:54.144+0100

It's not that they don't match. They're the same date. Event date is in UTC, so +0000, while Time capture there is in UTC+1, so +0100. If you want to convert Time Capture into UTC you need to remove one hour, and then event date and time capture match.

Sorry for not realizing before about it...but then...I think the app is sending proper data. Can you confirm that it's ok? If you do so, we will generate a new buddybuild changing Time Capture to be the creation date and not the completion date as it was before, and then you can validate that everything's ok and we can upload to GPlay.

Thanks!

**Comment by rbeccapotter** [comment]
Technically it makes sense, yes... from the program's perspective,  I don't like it because it puts events in the wrong month (albeit very rarely). 

Anyways, I'm not that worried about Time Capture and complete date. Let's just move forward with a release. Thanks for looking into it.

**Comment by ifoche** [comment]
Coming back to this comment, just for the record. That looks like a bug in the DHIS2 app you're using to show the events, right? If the event date is only allowed in UTC time, in DHIS2 (and that makes sense), I guess it's because all the DHIS2 apps should know that and show the information accordingly. So if you're showing the events for a concrete month, the app you're using should take that into account and show you the information depending on your timezone, or provide any "timezone" setting to use in the analysis.

Thank you for your detailed reports!
