### ISSUE TITLE
Default 0.0 GPS coordinates

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/SurveillanceLaosApp#55]
Less critical question about default GPS coordinates: is 18.560019, 107.345912 the new default coordinates for LA MCS (to distinguish from default Cambodia which is in the Gulf of Thailand)? With field testing in the Dev server, I have also seen coordinates of 0,0 show up. Is this another default possibility based on configuration of the provider's phone - i.e. out of our control?

**Comment by ifoche** [comment]
@rbeccapotter  In principle, no 0.0 coordinates should show up, so I guess you found a bug. We will look at it but in the meantime, do you have any device with 0.0 default coordinates to export its DB?

**Comment by rbeccapotter** [comment]
I haven't been able to reproduce this with the new build; I saw it happening on old versions that were being field tested -- so maybe it's fixed (?). We can keep this in the backlog and revisit if it persists.

For future reference, attaching a file I pulled from event report in data.psi-mis.org.  It's strange because sometimes a provider with the same phone (based on the Phone feature control DE) can submit events with GPS, or sometimes with 0,0. Or sometimes blank.
[Uploading LA dta quality check_mcs ONLY.xlsx...]

**Comment by ifoche** [comment]
@rbeccapotter diving a bit in the code, there's a change we made the 3/4/17, that is probably fixing that problem and that may be at the origin of the previous null values on GPS coordinates. Before that code fix we were not checking null GPS values returned by the phone, so if for any reason the phone was giving us a null value, instead of changing it into the default coordinates, we were probably setting a null (so 0) in GPS coordinates. So I would say that it's probably already fixed. But I like your idea of keeping it in backlog for a while to keep an eye on it just in case. I move it there
