### ISSUE TITLE
Exit pop up message translation issue

### ISSUE THREAD

**Issue by Vbouasone** [EyeSeeTea/SurveillanceLaosApp#56]
Exit pop up message when we want to close the MCS Lao app, it contains Lao with wrong translation. e.g: Really Exit? and Are you sure you want to exit the app?
Could you please use the translation in the HNQIS lao app in PO Editor

**Comment by Vbouasone** [comment]
![Really exit, pop up mgs.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/597962c4fd285a001abb776d/125516c66e82c728ace21e0d46da919b2f8e9ae98af1b657e81de09b390632636909a43832c9a138ad4d71040c1b5ca6535d5843f8aa8f2fafb76e25830d5fefd46d5e25cf3415a5ea9003ad43eb7edf10d8eff6df0ed2e22f24ef818e4a3e1a01118aff5537a19049da15.jpeg)

**Comment by rbeccapotter** [comment]
@ifoche Bouasone is saying that

1) the string 'survey_info_exit' is correctly translated in POeditor, but rendering incorrectly on the app. Can you refresh the translations from POeditor 

2) We can't find a string for "Really exit?" in POeditor for QIS LA -- which also is rendering a bad translation. But Bouasone says he has seen made this translation for HNQIS POeditor. So I don't know if it's possible we are crossings strings between apps or something.

Thanks!

**Comment by ifoche** [comment]
@rbeccapotter may @Vbouasone be confusing HNQIS with MCS Laos project? I can see the string [updated in HNQIS](https://poeditor.com/projects/po_edit?order=&filter=&id=46637&id_language=91&search=survey_title) from 2 weeks ago, but not in [QIS LA project](https://poeditor.com/projects/po_edit?order=&filter=&id=63217&id_language=91&search=survey_info_exit) where the last translation is from 11 months ago. To see the time from last translation, just pass your mouse over the term and it will appear on top of it.

As for the "really exit" string, you're completely right. We didn't see any update in the translations since 11 months ago, so we didn't even sync the translations. We will update POEditor with the new terms for you to be able to translate also the "Really exit" one. 

So we need to do 3 things:
1) We update the terms in POEditor (so you will have really exit to translate)
2) You translate really exit and any other term you would like to change
3) We update the app and publish a new bb

I'll let you know once 1) is done and wait for your confirmation that 2) is done before starting 3). Does it work for you?

**Comment by rbeccapotter** [comment]
Yup, that works. Thanks!

**Comment by ifoche** [comment]
@rbeccapotter, @Vbouasone, the terms are now updated. To change the term "Really exit?" just look for the key "confirmation_really_exit_title". 

I'll wait for you to confirm that all the translations are done to create a new release with your translations. 

Thanks!

**Comment by Vbouasone** [comment]
@ifoche <https://github.com/ifoche> I have done the translation in POeditor
for QIS LA Surveillance, one more thing if you could tell me the estimated
time of a new release will be helpful for Lao Malaria team to manage their
time in order to install the new version of MCS lao app for all PPMs in
Laos.

Thanks,

**Comment by ifoche** [comment]
@Vbouasone I'm now integrating the new translations. They will be available very soon in a new bb build. However, I see the term confirmation_really_exit_title untouched, and only modifications in Pv, Pf, Mixed, Positivity Rate and Negative. Is that correct?

**Comment by ifoche** [comment]
The new release is generated in bb. Please @rbeccapotter, @Vbouasone just give me the green light when I can upgrade to GPlay if you consider we can proceed.

**Comment by Vbouasone** [comment]
I am testing on the build # 41,  where can I find this term "confirmation_really_exit_title"? in QIS LA Surveillance or HNQIS?

**Comment by ifoche** [comment]
@Vbouasone if you click back button while in the app dashboard you should see that pop-up message with the confirmation_really_exit_title as the title of the pop-up, and confirmation_really_exit as the content of the pop-up

**Comment by ifoche** [comment]
I see that you've just translated the term, so you found it

**Comment by Vbouasone** [comment]
Yes, I got it

**Comment by ifoche** [comment]
So...Should I generate a new release for that term translation? Do you want to review all the terms again before I do it?

**Comment by Vbouasone** [comment]
before you generate a new release could you please update Lao language on the term "malaria_case_based_reporting" I made a small change in it based on government partner  needs us to change?

**Comment by ifoche** [comment]
ok, once I will export all the terms I will get that term too. I guess you don't need to review any other term. I can see 8 terms updated 2 hours ago, so those terms will be included in the new version.

**Comment by ifoche** [comment]
@Vbouasone, @rbeccapotter, I've deployed build 42 on bb taking the last translations into account. Please let me know by moving all cards to "Done" column or commenting this issue when you're ok for us to deploy to Google Play.

**Comment by Vbouasone** [comment]
I have tested and every thing is perfect! please deploy to Google Play.
